name: Docker Image & Push to Docker Hub and incremenet version

on:
  push:
    branches: ['master']

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from Repo
      uses: actions/checkout@v4

    - name: Get next version
      uses: reecetech/version-increment@2023.9.3
      id: version
      with:
        scheme: semver
        increment: patch
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: gerrity95/youtube_backend:${{ steps.version.outputs.version }},gerrity95/youtube_backend:latest

